services:
  - type: web
    name: s3-image-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --worker-class sync --max-requests 1000 --max-requests-jitter 100 --preload
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: GUNICORN_CMD_ARGS
        value: "--timeout=120 --workers=1 --worker-class=sync --max-requests=1000 --max-requests-jitter=100 --preload" 